Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net.Mime;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using GrabzIt;
using SinglePageCMS.Models;
using System.Net;
using System.Drawing;
using System.IO;

namespace SinglePageCMS.Controllers
{
    public class AdminController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Admin
        public ActionResult Index()
        {
            var persian = new PersianCalendar();
            var allInsight = db.Insights.ToList();
            DateTime week = DateTime.Now.AddDays(-7);

            var saturday = allInsight.Where(x => x.DateTime.Year == DateTime.Now.Year && x.DateTime.Month == DateTime.Now.Month && x.DateTime >= week).ToList().Where(x => x.DateTime.DayOfWeek.ToString() == DayOfWeek.Saturday.ToString()).Count();
            var sunday = allInsight.Where(x => x.DateTime.Year == DateTime.Now.Year && x.DateTime.Month == DateTime.Now.Month && x.DateTime >= week).ToList().Where(x => x.DateTime.DayOfWeek.ToString() == DayOfWeek.Sunday.ToString()).Count();
            var monday = allInsight.Where(x => x.DateTime.Year == DateTime.Now.Year && x.DateTime.Month == DateTime.Now.Month && x.DateTime >= week).ToList().Where(x => x.DateTime.DayOfWeek.ToString() == DayOfWeek.Monday.ToString()).Count();
            var tuesday = allInsight.Where(x => x.DateTime.Year == DateTime.Now.Year && x.DateTime.Month == DateTime.Now.Month && x.DateTime >= week).ToList().Where(x => x.DateTime.DayOfWeek.ToString() == DayOfWeek.Tuesday.ToString()).Count();
            var wednesday = allInsight.Where(x => x.DateTime.Year == DateTime.Now.Year && x.DateTime.Month == DateTime.Now.Month && x.DateTime >= week).ToList().Where(x => x.DateTime.DayOfWeek.ToString() == DayOfWeek.Wednesday.ToString()).Count();
            var thursday = allInsight.Where(x => x.DateTime.Year == DateTime.Now.Year && x.DateTime.Month == DateTime.Now.Month && x.DateTime >= week).ToList().Where(x => x.DateTime.DayOfWeek.ToString() == DayOfWeek.Thursday.ToString()).Count();
            var friday = allInsight.Where(x => x.DateTime.Year == DateTime.Now.Year && x.DateTime.Month == DateTime.Now.Month && x.DateTime >= week).ToList().Where(x => x.DateTime.DayOfWeek.ToString() == DayOfWeek.Friday.ToString()).Count();



            var farvardin = allInsight.Where(x => persian.GetYear(x.DateTime) == persian.GetYear(DateTime.Now) && persian.GetMonth(x.DateTime) == 1).Count();
            var ordibehesht = allInsight.Where(x => persian.GetYear(x.DateTime) == persian.GetYear(DateTime.Now) && persian.GetMonth(x.DateTime) == 2).Count();
            var khordad = allInsight.Where(x => persian.GetYear(x.DateTime) == persian.GetYear(DateTime.Now) && persian.GetMonth(x.DateTime) == 3).Count();
            var tir = allInsight.Where(x => persian.GetYear(x.DateTime) == persian.GetYear(DateTime.Now) && persian.GetMonth(x.DateTime) == 4).Count();
            var mordad = allInsight.Where(x => persian.GetYear(x.DateTime) == persian.GetYear(DateTime.Now) && persian.GetMonth(x.DateTime) == 5).Count();
            var shahrivar = allInsight.Where(x => persian.GetYear(x.DateTime) == persian.GetYear(DateTime.Now) && persian.GetMonth(x.DateTime) == 6).Count();
            var mehr = allInsight.Where(x => persian.GetYear(x.DateTime) == persian.GetYear(DateTime.Now) && persian.GetMonth(x.DateTime) == 7).Count();
            var aban = allInsight.Where(x => persian.GetYear(x.DateTime) == persian.GetYear(DateTime.Now) && persian.GetMonth(x.DateTime) == 8).Count();
            var azar = allInsight.Where(x => persian.GetYear(x.DateTime) == persian.GetYear(DateTime.Now) && persian.GetMonth(x.DateTime) == 9).Count();
            var dey = allInsight.Where(x => persian.GetYear(x.DateTime) == persian.GetYear(DateTime.Now) && persian.GetMonth(x.DateTime) == 10).Count();
            var bahman = allInsight.Where(x => persian.GetYear(x.DateTime) == persian.GetYear(DateTime.Now) && persian.GetMonth(x.DateTime) == 11).Count();
            var esfand = allInsight.Where(x => persian.GetYear(x.DateTime) == persian.GetYear(DateTime.Now) && persian.GetMonth(x.DateTime) == 12).Count();

            var h0 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 0 && x.DateTime.Hour < 1).Count();
            var h1 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 1 && x.DateTime.Hour < 2).Count();
            var h2 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 2 && x.DateTime.Hour < 3).Count();
            var h3 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 3 && x.DateTime.Hour < 4).Count();
            var h4 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 4 && x.DateTime.Hour < 5).Count();
            var h5 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 5 && x.DateTime.Hour < 6).Count();
            var h6 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 6 && x.DateTime.Hour < 7).Count();
            var h7 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 7 && x.DateTime.Hour < 8).Count();
            var h8 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 8 && x.DateTime.Hour < 9).Count();
            var h9 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 9 && x.DateTime.Hour < 10).Count();
            var h10 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 10 && x.DateTime.Hour < 11).Count();
            var h11 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 11 && x.DateTime.Hour < 12).Count();
            var h12 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 12 && x.DateTime.Hour < 13).Count();
            var h13 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 13 && x.DateTime.Hour < 14).Count();
            var h14 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 14 && x.DateTime.Hour < 15).Count();
            var h15 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 15 && x.DateTime.Hour < 16).Count();
            var h16 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 16 && x.DateTime.Hour < 17).Count();
            var h17 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 17 && x.DateTime.Hour < 18).Count();
            var h18 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 18 && x.DateTime.Hour < 19).Count();
            var h19 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 19 && x.DateTime.Hour < 20).Count();
            var h20 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 20 && x.DateTime.Hour < 21).Count();
            var h21 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 21 && x.DateTime.Hour < 22).Count();
            var h22 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 22 && x.DateTime.Hour < 23).Count();
            var h23 = allInsight.Where(x => x.DateTime.Date == DateTime.Now.Date && x.DateTime.Hour >= 23).Count();

            var all = allInsight.Count();
            var thisweek = allInsight.Where(insight => insight.DateTime.AddDays(7).Date >= DateTime.Now.Date).Count();
            var thismonth = allInsight.Where(insight => insight.DateTime.AddDays(30).Date >= DateTime.Now.Date).Count();



            //For Sending Data To View

            ViewBag.saturday = saturday;
            ViewBag.sunday = sunday;
            ViewBag.monday = monday;
            ViewBag.tuesday = tuesday;
            ViewBag.wednesday = wednesday;
            ViewBag.thursday = thursday;
            ViewBag.friday = friday;

            ViewBag.farvardin = farvardin;
            ViewBag.ordibehesht = ordibehesht;
            ViewBag.khordad = khordad;
            ViewBag.tir = tir;
            ViewBag.mordad = mordad;
            ViewBag.shahrivar = shahrivar;
            ViewBag.mehr = mehr;
            ViewBag.aban = aban;
            ViewBag.azar = azar;
            ViewBag.dey = dey;
            ViewBag.bahman = bahman;
            ViewBag.esfand = esfand;

            ViewBag.h0 = h0;
            ViewBag.h1 = h1;
            ViewBag.h2 = h2;
            ViewBag.h3 = h3;
            ViewBag.h4 = h4;
            ViewBag.h5 = h5;
            ViewBag.h6 = h6;
            ViewBag.h7 = h7;
            ViewBag.h8 = h8;
            ViewBag.h9 = h9;
            ViewBag.h10 = h10;
            ViewBag.h11 = h11;
            ViewBag.h12 = h12;
            ViewBag.h13 = h13;
            ViewBag.h14 = h14;
            ViewBag.h15 = h15;
            ViewBag.h16 = h16;
            ViewBag.h17 = h17;
            ViewBag.h18 = h18;
            ViewBag.h19 = h19;
            ViewBag.h20 = h20;
            ViewBag.h21 = h21;
            ViewBag.h22 = h22;
            ViewBag.h23 = h23;

            ViewBag.yesterdayh0 = allInsight.Where(x => x.DateTime.AddDays(1).Date == DateTime.Now.Date && x.DateTime.Hour >= 0 && x.DateTime.Hour < 1).Count();
            ViewBag.yesterdayh1 = allInsight.Where(x => x.DateTime.AddDays(1).Date == DateTime.Now.Date && x.DateTime.Hour >= 1 && x.DateTime.Hour < 2).Count();
            ViewBag.yesterdayh2 = allInsight.Where(x => x.DateTime.AddDays(1).Date == DateTime.Now.Date && x.DateTime.Hour >= 2 && x.DateTime.Hour < 3).Count();
            ViewBag.yesterdayh3 = allInsight.Where(x => x.DateTime.AddDays(1).Date == DateTime.Now.Date && x.DateTime.Hour >= 3 && x.DateTime.Hour < 4).Count();

Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SinglePageCMS.Models;

namespace SinglePageCMS.Controllers
{

    public class BlogsController : Controller
    {
        public ApplicationDbContext db = new ApplicationDbContext();
        // GET: Blogs
        public ActionResult Index()
        {
            return View(db.Blogs.ToList());
        }

        // GET: Blogs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // GET: Blogs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Blogs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Slug,Title,ContentData,Summery,Keywords")] Blog blog)
        {
            blog.CreateTime = DateTime.Now;
            blog.Modified = DateTime.Now;
            blog.GooglePlusId = db.Registeries.Find("GoogleId").Value;
            blog.Author = db.Registeries.Find("ApplicationName").Value;
            blog.UserId = User.Identity.GetUserId();
            blog.UserName = User.Identity.GetUserName();
            if (ModelState.IsValid)
            {
                db.Blogs.Add(blog);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blog);
        }

        // GET: Blogs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Slug,Title,ContentData,Summery,GooglePlusId,Author,UserName,UserId,Keywords,Modified,CreateTime")] Blog blog)
        {
            blog.Modified = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.Entry(blog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blog);
        }

        // GET: Blogs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Blog blog = db.Blogs.Find(id);
            db.Blogs.Remove(blog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SinglePageCMS.Models;

namespace SinglePageCMS.Controllers
{
    public class MenuController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Menu
        public ActionResult Index()
        {
            return View(db.Menus.ToList());
        }

        // GET: Menu/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // GET: Menu/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Menu/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Url")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                db.Menus.Add(menu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(menu);
        }

        // GET: Menu/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Menu/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Url")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(menu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(menu);
        }

        // GET: Menu/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Menu/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Menu menu = db.Menus.Find(id);
            db.Menus.Remove(menu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_AdminLayout.cshtml
@using SinglePageCMS.Models
@{
    ApplicationDbContext db = new ApplicationDbContext();
}
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - پنل مدیریت</title>
    @if (db.Registeries.Find("Logo") != null)
    {
        <link rel="shortcut icon" href="@db.Registeries.Find("Logo").Value"/>
    }
    @Styles.Render("~/Content/Admin")
    <link rel="stylesheet" href="~/Content/font-awesome/css/font-awesome.min.css">
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/Chart/Chart.min.js"></script>
    <script>
        $.ajaxSetup({ 'global': true });
    </script>
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <header>
        <div class="head-well">
            @Html.Action("Clock", "Admin")
        </div>
        <ul class="header-menu">
            <li>@Html.ActionLink("نمای اصلی سایت", "Index", "Home", null, new { @target = "blank" })</li>
        </ul>
    </header>
    <div class="menu-sidebar">
        <ul class="sidebar-menu-parent">
            @if (db.Registeries.Find("Logo") != null && !String.IsNullOrEmpty(db.Registeries.Find("Logo").Value))
            {
                <li class="logo-user-li"></li>
            }
            else
            {
                <li class="logo-li"></li>
            }

            <li class="sidebar-menu-item"><p><i style="color:#777" class="fa fa-home fa-2x"></i>@Html.ActionLink("صفحه اصلی", "Index", "Admin")</p></li>
            <li class="sidebar-menu-item"><p><i style="color:#777" class="fa fa-bars fa-2x"></i>@Html.ActionLink("تنظیمات مربوط به صفحه اصلی", "HomePage", "Admin")</p></li>
            <li class="sidebar-menu-item"><p><i style="color:#777" class="fa fa-th-large fa-2x"></i>@Html.ActionLink("مدیریت رسانه", "Index", "Image")</p></li>
            <li class="sidebar-menu-item"><p><i style="color:#777" class="fa fa-gear fa-2x"></i>@Html.ActionLink("تنظیمات اصلی سایت", "Index", "SetDefaults")</p></li>
            <li class="sidebar-menu-item"><p><i style="color:#777" class="fa fa-file-text  fa-2x"></i>@Html.ActionLink("مطالب سایت", "Index", "Contents")</p></li>
            <li class="sidebar-menu-item"><p><i style="color:#777" class="fa fa-edit fa-2x"></i>@Html.ActionLink("مدیریت وبلاگ", "Index", "Blogs")</p></li>
            <li class="sidebar-menu-item"><p><i style="color:#777" class="fa fa-users fa-2x"></i>@Html.ActionLink("مدیریت کاربران", "Index", "UsersAdmin")</p></li>
            <li class="sidebar-menu-item"><p><i style="color:#777" class="fa fa-bars fa-2x"></i>@Html.ActionLink("مدیریت منو", "Index", "Menu")</p></li>
            @*<li class="sidebar-menu-item"><p><i style="color:#777" class="fa fa-send fa-2x"></i>@Html.ActionLink("اطلاع رسانی", "Index", "Admin")</p></li>*@
            @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
            {
                @Html.AntiForgeryToken()
                <li class="sidebar-menu-item"><p><i style="color:#777" class="fa fa-2x fa-arrow-circle-right"></i><a href="javascript:document.getElementById('logoutForm').submit()">خروج</a></p></li>
            }
        </ul>
    </div>
    <div class="container">
        <div class="content">
            @RenderBody()
        </div>
    </div>
    @RenderSection("BackToList", required: false)
    <footer>
        Tenzo CMS - &copy; @DateTime.Now.Year
    </footer>
    @RenderSection("Scripts", required: false)
    @Html.Action("GetData", "Insight")
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @Html.Action("GetData","Insight")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>