Controllers/SetDefaultsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SinglePageCMS.Models;

namespace SinglePageCMS.Controllers
{
    public class SetDefaultsController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: SetDefaults

        public ActionResult Index()
        {
            var s = db.Registeries.ToList();
            if (s.Count > 10)
            {
                var appname = db.Registeries.Find("ApplicationName").Value;
                var email = db.Registeries.Find("EmailAddress").Value;
                var address = db.Registeries.Find("Address").Value;
                var phonenumber = db.Registeries.Find("PhoneNumber").Value;
                var logo = db.Registeries.Find("Logo").Value;
                var googleId = db.Registeries.Find("GoogleId").Value;
                var fb = db.Registeries.Find("FacebookUrl").Value;
                var insta = db.Registeries.Find("InstagramUrl").Value;
                var googleUrl = db.Registeries.Find("GoogleUrl").Value;
                var publish = db.Registeries.Find("Publish").Value;

                ViewBag.address = false;
                ViewBag.appname = false;
                ViewBag.email = false;
                ViewBag.fb = false;
                ViewBag.googleId = false;
                ViewBag.insta = false;
                ViewBag.googleUrl = false;
                ViewBag.logo = false;
                ViewBag.phonenumber = false;
                ViewBag.publish = false;
                if (publish == "false")
                {
                    ViewBag.publish = true;
                }
                if (String.IsNullOrEmpty(googleUrl))
                {
                    ViewBag.googleUrl = true;
                }
                if (String.IsNullOrEmpty(googleId))
                {
                    ViewBag.googleId = true;
                }
                if (String.IsNullOrEmpty(insta))
                {
                    ViewBag.insta = true;
                }
                if (String.IsNullOrEmpty(fb))
                {
                    ViewBag.fb = true;
                }
                if (String.IsNullOrEmpty(logo))
                {
                    ViewBag.logo = true;
                }
                if (String.IsNullOrEmpty(phonenumber))
                {
                    ViewBag.phonenumber = true;
                }
                if (String.IsNullOrEmpty(address))
                {
                    ViewBag.address = true;
                }
                if (String.IsNullOrEmpty(email))
                {
                    ViewBag.email = true;
                }
                if (String.IsNullOrEmpty(appname))
                {
                    ViewBag.appname = true;
                }
            }
            return View();
        }

        public ActionResult Step1()
        {
            ViewBag.Title = "نام سایت";
            var data = db.Registeries.Find("ApplicationName");
            if (data == null)
            {
                return PartialView();
            }
            return PartialView(data);
        }

        [HttpPost]
        public ActionResult Step1(Registery model)
        {
            ViewBag.Title = "نام سایت";
            if (ModelState.IsValid)
            {
                if (String.IsNullOrEmpty(model.Name))
                {
                    model.Name = "ApplicationName";
                    db.Entry(model).State = EntityState.Added;
                    db.SaveChanges();
                }
                else
                {
                    db.Entry(model).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            return PartialView(model);
        }

        public ActionResult Step2()
        {
            ViewBag.Title = "ایمیل سایت";
            var data = db.Registeries.Find("EmailAddress");
            if (data == null)
            {
                return PartialView();
            }
            return PartialView(data);
        }

        [HttpPost]
        public ActionResult Step2(Registery model)
        {
            ViewBag.Title = "ایمیل سایت";
            if (ModelState.IsValid)
            {
                if (String.IsNullOrEmpty(model.Name))
                {
                    model.Name = "EmailAddress";
                    db.Entry(model).State = EntityState.Added;
                    db.SaveChanges();
                }
                else
                {
                    db.Entry(model).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            return PartialView(model);
        }

        public ActionResult Step3()
        {
            ViewBag.Title = "آدرس";
            var data = db.Registeries.Find("Address");
            if (data != null)
            {
                return PartialView(data);
            }
            return PartialView();
        }

        [HttpPost]
        public ActionResult Step3(Registery model)
        {
            ViewBag.Title = "آدرس";
            if (ModelState.IsValid)
            {
                if (String.IsNullOrEmpty(model.Name))
                {
                    model.Name = "Address";
                    db.Entry(model).State = EntityState.Added;
                    db.SaveChanges();
                }
                else
                {
                    db.Entry(model).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            return PartialView(model);
        }

        public ActionResult Step4()
        {
            ViewBag.Title = "شماره تماس";
            var data = db.Registeries.Find("PhoneNumber");
            if (data != null)
            {
                return PartialView(data);
            }
            return PartialView();
        }

        [HttpPost]
        public ActionResult Step4(Registery model)
        {
            ViewBag.Title = "شماره تماس";
            if (ModelState.IsValid)
            {
                if (String.IsNullOrEmpty(model.Name))
                {
                    model.Name = "PhoneNumber";
                    db.Entry(model).State = EntityState.Added;
                    db.SaveChanges();
                }
                else
                {
                    db.Entry(model).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            return PartialView(model);
        }

        public ActionResult Step5()
        {
            ViewBag.Title = "لوگو سایت";

            var data = db.Registeries.Find("Logo");
            if (data != null)
            {
                return PartialView(data);
            }
            var empty = new Registery();
            empty.Value = "Empty";
            return PartialView(empty);
        }

        [HttpPost]
        public ActionResult Step5(Registery model, HttpPostedFileBase file)
        {
            ViewBag.Title = "لوگو سایت";
            var imageName = "Logo";
            if (file != null)
            {
                var directory = Server.MapPath("~/Uploads/Logo/");
                Directory.CreateDirectory(directory);
                var fileType = Path.GetExtension(file.FileName);
                var imageUrl = imageName + fileType;
                var path = Path.Combine(Server.MapPath("~/Uploads/Logo"), imageUrl);
                file.SaveAs(path);
                model.Value = "/Uploads/Logo/" + imageUrl;
            }
            if (ModelState.IsValid)
            {
                if (String.IsNullOrEmpty(model.Name))
                {

                    model.Name = "Logo";
                    db.Entry(model).State = EntityState.Added;
                    db.SaveChanges();
                }
                else
                {
                    db.Entry(model).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            return PartialView(model);
        }

        public ActionResult Step6()
        {
            ViewBag.Title = "آی دی گوگل";
            ViewBag.Caution = "آی دی گوگل پلاس را وارد کنید، از وارد کردن آدرس صفحه اجتناب کنید.";
            var data = db.Registeries.Find("GoogleId");
            if (data != null)
            {
                return PartialView(data);
            }
            return PartialView();
        }

        [HttpPost]
        public ActionResult Step6(Registery model)
        {
            ViewBag.Title = "آی دی گوگل";
            ViewBag.Caution = "آی دی گوگل پلاس را وارد کنید، از وارد کردن آدرس صفحه اجتناب کنید.";
            if (ModelState.IsValid)
            {
                if (String.IsNullOrEmpty(model.Name))
                {
                    model.Name = "GoogleId";
                    db.Entry(model).State = EntityState.Added;
                    db.SaveChanges();
                }
                else
                {
                    db.Entry(model).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            return PartialView(model);
        }

        public ActionResult Step7()
        {
            ViewBag.Title = "آدرس فیس بوک";
            var data = db.Registeries.Find("FacebookUrl");
            if (data != null)
            {
                return PartialView(data);
            }
            return PartialView();
        }

        [HttpPost]
        public ActionResult Step7(Registery model)
        {

Views/SetDefaults/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            //$(function load() {
            //    LoadStep1();
            //});
            $('#loading').hide();
        });

        var $loading = $('#loading').hide();
        $(document)
          .ajaxStart(function () {
              $('.ajaxBox').empty();
              $loading.show();
          })
          .ajaxStop(function () {
              $loading.hide();
          });

        //$(document).ajaxStart(function () {
        //    $('.ajaxBox').empty();
        //    $(".loading").show();
        //});

        //$(document).ajaxComplete(function () {
        //    $(".loading").hide();
        //});

        function loading() {
            $('#loading').show();
        }

        function complete() {
            $('#loading').hide();
        }

        function LoadStep1() {
            var myDiv = $('.ajaxBox');
            $.ajax({
                url: '@Url.Action("Step1", "SetDefaults")',
                type: 'GET',
                cache: false,
                context: myDiv,
                success: function (result) {
                    $('.ajaxBox').html(result);
                }
            });
        }

        function LoadStep2() {
            var myDiv = $('.ajaxBox');
            $.ajax({
                url: '@Url.Action("Step2", "SetDefaults")',
                type: 'GET',
                cache: false,
                context: myDiv,
                success: function (result) {
                    $('.ajaxBox').html(result);
                }
            });
        }

        function LoadStep3() {
            var myDiv = $('.ajaxBox');
            $.ajax({
                url: '@Url.Action("Step3", "SetDefaults")',
                type: 'GET',
                cache: false,
                context: myDiv,
                success: function (result) {
                    $('.ajaxBox').html(result);
                }
            });
        }

        function LoadStep4() {
            var myDiv = $('.ajaxBox');
            $.ajax({
                url: '@Url.Action("Step4", "SetDefaults")',
                type: 'GET',
                cache: false,
                context: myDiv,
                success: function (result) {
                    $('.ajaxBox').html(result);
                }
            });
        }

        function LoadStep5() {
            var myDiv = $('.ajaxBox');
            $.ajax({
                url: '@Url.Action("Step5", "SetDefaults")',
                type: 'GET',
                cache: false,
                context: myDiv,
                success: function (result) {
                    $('.ajaxBox').html(result);
                }
            });
        }

        function LoadStep6() {
            var myDiv = $('.ajaxBox');
            $.ajax({
                url: '@Url.Action("Step6", "SetDefaults")',
                type: 'GET',
                cache: false,
                context: myDiv,
                success: function (result) {
                    $('.ajaxBox').html(result);
                }
            });
        }

        function LoadStep7() {
            var myDiv = $('.ajaxBox');
            $.ajax({
                url: '@Url.Action("Step7", "SetDefaults")',
                type: 'GET',
                cache: false,
                context: myDiv,
                success: function (result) {
                    $('.ajaxBox').html(result);
                }
            });
        }

        function LoadStep8() {
            var myDiv = $('.ajaxBox');
            $.ajax({
                url: '@Url.Action("Step8", "SetDefaults")',
                type: 'GET',
                cache: false,
                context: myDiv,
                success: function (result) {
                    $('.ajaxBox').html(result);
                }
            });
        }

        function LoadStep9() {
            var myDiv = $('.ajaxBox');
            $.ajax({
                url: '@Url.Action("Step9", "SetDefaults")',
                type: 'GET',
                cache: false,
                context: myDiv,
                success: function (result) {
                    $('.ajaxBox').html(result);
                }
            });
        }

        function LoadStep10() {
            var myDiv = $('.ajaxBox');
            $.ajax({
                url: '@Url.Action("Step10", "SetDefaults")',
                type: 'GET',
                cache: false,
                onLoading: loading,
                context: myDiv,
                success: function (result) {
                    complete();
                    $('.ajaxBox').html(result);
                }
            });
        }





    </script>
}

<h1>تنظیمات اصلی سایت</h1>

<section class="setdefault">
    @if (ViewBag.appname != null)
    {
        <button id="step1" onclick="LoadStep1();" class="caution">نام سایت</button>
        @*@Html.ActionLink("نام سایت", "Step1", new { @class = "caution" })*@
    }
    else
    {
        <button id="step1" onclick="LoadStep1();">نام سایت</button>
        @*@Html.ActionLink("نام سایت", "Step1")*@
    }
    @if (ViewBag.email != null)
    {
        <button id="step2" class="caution" onclick="LoadStep2();">آدرس ایمیل</button>
        @*@Html.ActionLink("آدرس ایمیل", "Step2", null, new { @class = "caution" })*@
    }
    else
    {
        <button id="step2" onclick="LoadStep2();">آدرس ایمیل</button>
        @*@Html.ActionLink("آدرس ایمیل", "Step2")*@
    }
    @if (ViewBag.address != null)
    {
        <button id="step3" onclick="LoadStep3();" class="caution">آدرس</button>
        @*@Html.ActionLink("آدرس", "Step3", null, new { @class = "caution" })*@
    }
    else
    {
        <button onclick="LoadStep3();" id="step3">آدرس</button>
        @*@Html.ActionLink("آدرس", "Step3")*@
    }
    @if (ViewBag.phonenumber != null)
    {
        <button id="step4" onclick="LoadStep4();" class="caution">شماره تماس</button>
        @*@Html.ActionLink("شماره تماس", "Step4", null, new { @class = "caution" })*@
    }
    else
    {
        <button onclick="LoadStep4();" id="step4">شماره تماس</button>
        @*@Html.ActionLink("شماره تماس", "Step4")*@
    }
    @if (ViewBag.logo != null)
    {
        <button onclick="LoadStep5();" id="step5" class="caution">لوگو سایت</button>
        @*@Html.ActionLink("لوگو سایت", "Step5", null, new { @class = "caution" })*@
    }
    else
    {
        <button onclick="LoadStep5();" id="step5">لوگو سایت</button>
        @*@Html.ActionLink("لوگو سایت", "Step5")*@
    }
    @if (ViewBag.googleId != null)
    {
        <button id="step6" onclick="LoadStep6();" class="caution">آی دی گوگل</button>
        @*@Html.ActionLink("آی دی گوگل", "Step6", null, new { @class = "caution" })*@
    }
    else
    {
        <button onclick="LoadStep6();" id="step6">آی دی گوگل</button>
        @*@Html.ActionLink("آی دی گوگل", "Step6")*@
    }
    @if (ViewBag.fb != null)
    {
        <button id="step7" onclick="LoadStep7();" class="caution">آدرس فیس بوک</button>
        @*@Html.ActionLink("آدرس فیس بوک", "Step7", null, new { @class = "caution" })*@
    }
    else
    {
        <button id="step7" onclick="LoadStep7();">آدرس فیس بوک</button>
        @*@Html.ActionLink("آدرس فیس بوک", "Step7")*@
    }
    @if (ViewBag.insta != null)
    {
        <button id="step8" onclick="LoadStep8();" class="caution">آدرس اینستاگرام</button>
        @*@Html.ActionLink("آدرس اینستاگرام", "Step8", null, new { @class = "caution" })*@
    }
    else
    {
        <button onclick="LoadStep8();" id="step8">آدرس اینستاگرام</button>
        @*@Html.ActionLink("آدرس اینستاگرام", "Step8")*@
    }
    @if (ViewBag.googleUrl != null)
    {
        <button id="step9" class="caution" onclick="LoadStep9();">آدرس گوگل پلاس</button>
        @*@Html.ActionLink("آدرس گوگل پلاس", "Step9", null, new { @class = "caution" })*@
    }
    else
    {
        <button id="step9" onclick="LoadStep9();">آدرس گوگل پلاس</button>
        @*@Html.ActionLink("آدرس گوگل پلاس", "Step9")*@
    }
    @if (ViewBag.publish != null)
    {
        <button id="step10" class="caution" onclick="LoadStep10();">انتشار سایت</button>
        @*@Html.ActionLink("انتشار سایت", "Step10", null, new { @class = "caution" })*@
    }
    else
    {
        <button id="step10" onclick="LoadStep10();">انتشار سایت</button>
        @*@Html.ActionLink("انتشار سایت", "Step10")*@
    }
</section>

<div id="loading"><i class="fa fa-spin fa-spinner fa-2x"></i></div>
<section class="ajaxBox"></section>

Views/SetDefaults/Step1.cshtml
@model SinglePageCMS.Models.Registery

<h3>@ViewBag.Title</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal admin-form">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Name)

        <div class="form-group">
            @Html.Label("نام سایت", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ذخیره" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/SetDefaults/Step10.cshtml
@model SinglePageCMS.Models.Registery



<h3>@ViewBag.Title</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal admin-form">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Name)

        <div class="form-group">
            @Html.Label("انتشار سایت", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="radio" value="True" name="Value" id="ValueTrue"> سایت را منتشر کن.<br/>
                <input type="radio" value="False" name="Value" id="ValueFalse"> سایت را منتشر نکن.
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ذخیره" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/SetDefaults/Step11.cshtml
@model SinglePageCMS.Models.Registery


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Name)

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ذخیره" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/SetDefaults/Step2.cshtml
@model SinglePageCMS.Models.Registery


<h3>@ViewBag.Title</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal admin-form">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Name)

        <div class="form-group">
            @Html.Label("آدرس ایمیل", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ذخیره" class="btn btn-default" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/SetDefaults/Step3.cshtml
@model SinglePageCMS.Models.Registery


<h3>@ViewBag.Title</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal admin-form">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Name)

        <div class="form-group">
            @Html.Label("آدرس", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ذخیره" class="btn btn-default" />
            </div>
        </div>
    </div>
}




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/SetDefaults/Step4.cshtml
@model SinglePageCMS.Models.Registery


<h3>@ViewBag.Title</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal admin-form">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Name)

        <div class="form-group">
            @Html.Label("شماره های تماس", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ذخیره" class="btn btn-default" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/SetDefaults/Step5.cshtml
@model SinglePageCMS.Models.Registery


<h3>@ViewBag.Title</h3>


@using (Html.BeginForm("Step5", "SetDefaults", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal admin-form">
        @*@Html.ValidationSummary(false, "", new { @class = "text-danger" })*@
        @Html.HiddenFor(model => model.Name)
        @Html.HiddenFor(model => model.Value)
        <div class="form-group">
            @Html.Label("لوگو سایت", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" id="file" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ذخیره" class="btn btn-default" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/SetDefaults/Step6.cshtml
@model SinglePageCMS.Models.Registery


<h3>@ViewBag.Title</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal admin-form">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Name)

        <div class="form-group">
            @Html.Label("آی دی گوگل", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ذخیره" class="btn btn-default" />
            </div>
        </div>
    </div>
}




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/SetDefaults/Step7.cshtml
@model SinglePageCMS.Models.Registery


<h3>@ViewBag.Title</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal admin-form">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Name)

        <div class="form-group">
            @Html.Label("آدرس صفحه فیس بوک", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ذخیره" class="btn btn-default" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/SetDefaults/Step8.cshtml
@model SinglePageCMS.Models.Registery


<h3>@ViewBag.Title</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal admin-form">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Name)

        <div class="form-group">
            @Html.Label("آدرس اینستاگرام", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ذخیره" class="btn btn-default" />
            </div>
        </div>
    </div>
}





@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/SetDefaults/Step9.cshtml
@model SinglePageCMS.Models.Registery


<h3>@ViewBag.Title</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal admin-form">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Name)

        <div class="form-group">
            @Html.Label("آدرس صفحه گوگل پلاس", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ذخیره" class="btn btn-default" />
            </div>
        </div>
    </div>
}




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}